# Generated by Django 3.1.5 on 2021-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dog_Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('gramos', models.CharField(max_length=8)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Eukanuba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('gramos', models.CharField(max_length=8)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('gramos', models.CharField(max_length=8)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('gramos', models.CharField(max_length=8)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sabrocitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('gramos', models.CharField(max_length=8)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
