# Generated by Django 3.1.5 on 2021-03-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dirección', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
                ('pedido', models.CharField(max_length=30)),
                ('cantidad', models.FloatField()),
                ('precio', models.IntegerField()),
                ('entrega', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='marca')),
                ('cantidad', models.FloatField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dog_Selection',
        ),
        migrations.DeleteModel(
            name='Eukanuba',
        ),
        migrations.DeleteModel(
            name='Pedigree',
        ),
        migrations.DeleteModel(
            name='Raza',
        ),
        migrations.DeleteModel(
            name='Sabrocitos',
        ),
    ]
