# Generated by Django 3.1.5 on 2021-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0003_auto_20210311_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default='anything'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
