# Generated by Django 3.1.5 on 2021-03-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0004_auto_20210311_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
