# Generated by Django 3.1.5 on 2021-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0005_auto_20210311_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.CharField(max_length=20),
        ),
    ]
