# Generated by Django 3.1.5 on 2021-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_', '0006_auto_20210311_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
